image IMAGE_TAG: build
    docker buildx build \
        --platform wasi/wasm32 \
        -f ../../../../docker/wasm.Dockerfile \
        -t {{IMAGE_TAG}} \
        --build-arg "EXE_NAME=auth-get-login.wasm" \
        ./tmp

build:
    rm -rf ./tmp
    cargo build --target wasm32-wasi --bin auth-get-login
    mkdir -p tmp
    cp ../../../../target/wasm32-wasi/debug/auth-get-login.wasm tmp/auth-get-login.wasm