allow_k8s_contexts(['knative'])
k8s_kind(
    'Service',
    api_version='serving.knative.dev/v1',
    image_json_path='{.spec.template.spec.containers[*].image}'
)

custom_build(
  'auth-get-login',
  'just image $EXPECTED_REF',
  ['.'],
  ignore=['tmp']
)

k8s_yaml(helm(
  '../../../../deploy/app',
  name='auth-get-login',
  namespace='default',
  set=[
    'name=auth-get-login',
    'image=auth-get-login'
  ]
))