[package]
name = "book_planner"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "src/wasm",
    "src/rust"
]

[dependencies]
book_planner_wasm = { path = "src/wasm"}
book_planner_rust = { path = "src/rust"}