apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: default
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "10"
    spec:
      runtimeClassName: crun
      containers:
      - name: wasm-app
        image: {{ .Values.image }}