[package]
name = "book_planner_tools"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "copy-wasms"
path = "cmd/copy-wasms.rs"

[dependencies]
serde = "1.0.159"
serde_derive = "1.0.159"
toml = "0.7.3"
